"""Add birth_date to Author and isbn to Book

Revision ID: 70758b1a2b07
Revises: f64a10281ff1
Create Date: 2024-12-29 04:42:14.274138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70758b1a2b07'
down_revision = 'f64a10281ff1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('books', sa.Column('isbn', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_column('books', 'isbn')
    op.drop_column('authors', 'birth_date')
    # ### end Alembic commands ###
